#!/bin/bash

# COMMAND=$(xset -q | grep LED | awk '{print $10}')
# case "$COMMAND" in
#     "00000000"|"00000001") LAYOUT="🇬🇧";;
#     "00001000"|"00001001") LAYOUT="🇩🇪";;
#     *) LAYOUT="??" ;;
# esac
# echo $LAYOUT

LAYOUT=$(setxkbmap -query | awk '/layout/ {print $2}')

if [[ "$LAYOUT" == "gb" ]]; then
    setxkbmap de
else
    setxkbmap gb
fi

setxkbmap -query | awk '/layout/ {print $2}'
